Make apt upgrade non-interactive for VM provisioning
Azure/iot-identity-service pull request #373
Opened 2022-02-24 19:12 UTC by gauravIoTEdge

This PR fixes persistent failures in ubuntu:18.04 jobs.

Currently, the VM provisioning process is unable to run **apt upgrade**, which in turn is because the upgrade of the openssh-server package is conflicting with files that are pre-installed on the VM image.

This change makes the upgrades non-interactive and automatically chooses the newer file(s) in case of any conflict (which is fine since it's a clean VM).

2022-02-24 20:10 UTC, arsing requested changes

2022-02-24 20:10 UTC, arsing commented on ci/e2e-tests/test-run.sh
> +            upgrade
```suggestion
            sudo DEBIAN_FRONTEND=noninteractive \
                apt-get \
                -o 'Dpkg::Options::=--force-confnew' \
                -o 'Dpkg::Options::=--force-confdef' \
                -y \
                --allow-downgrades \
                --allow-remove-essential \
                --allow-change-held-packages \
                upgrade
```

2022-02-24 20:11 UTC, arsing commented
>Ran E2E tests and a couple of 18.04 jobs passed, unlike before.

Please share the link.

2022-02-25 23:54 UTC, gauravIoTEdge commented
> > Ran E2E tests and a couple of 18.04 jobs passed, unlike before.
> 
> Please share the link.

Link is in testing notes.

2022-02-26 00:00 UTC, arsing approved these changes
Thanks, looks to be fixed. Please get an approval from Gordon too before you apply the ready-to-merge label.

2022-02-26 00:08 UTC, gordonwang0 approved these changes

2022-02-26 00:09 UTC, merged